services:
  - type: web
    name: asr-work-order-form
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PASSWORD
        sync: false
